doc: add search bar
zkmopro/mopro pull request #229
Opened 2024-08-02 20:18 UTC by vivianjeng

- add docusaurus search bar

2024-08-06 17:51 UTC, chancehudson commented
The highlight color in the popup is white and it makes the text unreasonable. Is it possible to change this?

![output](https://github.com/user-attachments/assets/b9a890fb-1988-4530-b4ee-042868f335d2)

2024-08-06 17:52 UTC, chancehudson requested changes
Search result highlighting, see other comment

2024-08-07 09:27 UTC, vivianjeng commented
@chancehudson done!
<img width="563" alt="截圖 2024-08-07 下午5 27 04" src="https://github.com/user-attachments/assets/e26dece3-55fa-439e-86f6-733d1e562523">

2024-08-08 17:46 UTC, chancehudson approved these changes

2024-08-08 17:46 UTC, merged